export enum ActionType {
  REFUND = 'refund',
  REJECT = 'reject',
  TRANSFER = 'transfer',
}

export enum IntegrationTypeEnum {
  BANKS = 'BANKS',
  LPS = 'LPS',
  EXCHANGE = 'EXCHANGE',
}

export enum PasswordFields {
  PASSWORD = 'password',
  TOS_PASSWORD = 'tosPassword',
  SECRET_KEY = 'secretKey',
  PASS_PHRASE = 'passPhrase',
}

export const PASSWORD_FIELD_VALUES = Object.values(PasswordFields);

export const refundCellEnum: any = {
  0: 'Bankadan Cevap Bekleniyor',
  1: 'İade Edildi',
  2: 'İade Edilemedi',
};

export const transferTypeEnum = [
  { value: 1, label: 'EFT' },
  { value: 2, label: 'Havale' },
  { value: 3, label: 'Fast' },
];

export const transferTimeEnum = [
  { value: 1, label: 'All' },
  { value: 2, label: 'Today' },
  { value: 3, label: 'Yesterday' },
  { value: 4, label: 'Last Week' },
  { value: 5, label: 'Last Month' },
];

export const activeEnum = [
  { value: true, label: 'Active' },
  { value: false, label: 'Passive' },
];

export const editProfileActionsEnum = [
  { value: '1', label: 'view' },
  { value: '2', label: 'create' },
  { value: '3', label: 'edit' },
  { value: '4', label: 'delete' },
];

export const entityTypeEnum = [
  { label: 'Personal', value: 0 },
  { label: 'Corporate', value: 1 },
];

export const channelEnum = [
  { label: 'VASP', value: 0 },
  { label: 'WALLET', value: 1 },
];

export const entityEnum = [
  { label: 'PERSONAL', value: 0 },
  { label: 'CORPORATE', value: 1 },
];

export const senderLpEnum = [
  { label: 'WhiteBit', value: 1 },
  { label: 'CoinTR', value: 2 },
  { label: 'OKX', value: 3 },
];

export const targetTypeEnum = [
  { label: 'OnChain', value: 1 },
  { label: 'InternalTransfer', value: 2 },
];

export const accountTypeEnum = [
  { label: 'Deposit', value: 'Deposit' },
  { label: 'Withdrawal', value: 'Withdraw' },
];

export const countryEnum = [
  { name: 'Afghanistan', value: 'AF' },
  { name: 'Albania', value: 'AL' },
  { name: 'Algeria', value: 'DZ' },
  { name: 'Andorra', value: 'AD' },
  { name: 'Angola', value: 'AO' },
  { name: 'Anguilla', value: 'AI' },
  { name: 'AntiguaAndBarbuda', value: 'AG' },
  { name: 'Argentina', value: 'AR' },
  { name: 'Armenia', value: 'AM' },
  { name: 'Australia', value: 'AU' },
  { name: 'Austria', value: 'AT' },
  { name: 'Azerbaijan', value: 'AZ' },
  { name: 'Bahamas', value: 'BS' },
  { name: 'Bahrain', value: 'BH' },
  { name: 'Bangladesh', value: 'BD' },
  { name: 'Barbados', value: 'BB' },
  { name: 'Belarus', value: 'BY' },
  { name: 'Belgium', value: 'BE' },
  { name: 'Belize', value: 'BZ' },
  { name: 'Benin', value: 'BJ' },
  { name: 'Bermuda', value: 'BM' },
  { name: 'Bhutan', value: 'BT' },
  { name: 'Bolivia', value: 'BO' },
  { name: 'BosniaAndHerzegovina', value: 'BA' },
  { name: 'Botswana', value: 'BW' },
  { name: 'Brazil', value: 'BR' },
  { name: 'BritishVirginIslands', value: 'VG' },
  { name: 'Brunei', value: 'BN' },
  { name: 'Bulgaria', value: 'BG' },
  { name: 'BurkinaFaso', value: 'BF' },
  { name: 'Burundi', value: 'BI' },
  { name: 'Cambodia', value: 'KH' },
  { name: 'Cameroon', value: 'CM' },
  { name: 'Canada', value: 'CA' },
  { name: 'CapeVerde', value: 'CV' },
  { name: 'CaymanIslands', value: 'KY' },
  { name: 'CentralAfricanRepublic', value: 'CF' },
  { name: 'Chad', value: 'TD' },
  { name: 'Chile', value: 'CL' },
  { name: 'Colombia', value: 'CO' },
  { name: 'Comoros', value: 'KM' },
  { name: 'CongoRepublic', value: 'CG' },
  { name: 'CongoDemocraticRepublic', value: 'CD' },
  { name: 'CostaRica', value: 'CR' },
  { name: 'CoteDIvoire', value: 'CI' },
  { name: 'Croatia', value: 'HR' },
  { name: 'Cuba', value: 'CU' },
  { name: 'Cyprus', value: 'CY' },
  { name: 'CzechRepublic', value: 'CZ' },
  { name: 'Denmark', value: 'DK' },
  { name: 'Djibouti', value: 'DJ' },
  { name: 'Dominica', value: 'DM' },
  { name: 'DominicanRepublic', value: 'DO' },
  { name: 'Ecuador', value: 'EC' },
  { name: 'Egypt', value: 'EG' },
  { name: 'ElSalvador', value: 'SV' },
  { name: 'EquatorialGuinea', value: 'GQ' },
  { name: 'Eritrea', value: 'ER' },
  { name: 'Estonia', value: 'EE' },
  { name: 'Ethiopia', value: 'ET' },
  { name: 'Fiji', value: 'FJ' },
  { name: 'Finland', value: 'FI' },
  { name: 'France', value: 'FR' },
  { name: 'Gabon', value: 'GA' },
  { name: 'Gambia', value: 'GM' },
  { name: 'Georgia', value: 'GE' },
  { name: 'Germany', value: 'DE' },
  { name: 'Ghana', value: 'GH' },
  { name: 'Greece', value: 'GR' },
  { name: 'Grenada', value: 'GD' },
  { name: 'Guatemala', value: 'GT' },
  { name: 'Guinea', value: 'GN' },
  { name: 'GuineaBissau', value: 'GW' },
  { name: 'Guyana', value: 'GY' },
  { name: 'Haiti', value: 'HT' },
  { name: 'Honduras', value: 'HN' },
  { name: 'HongKong', value: 'HK' },
  { name: 'Hungary', value: 'HU' },
  { name: 'Iceland', value: 'IS' },
  { name: 'India', value: 'IN' },
  { name: 'Indonesia', value: 'ID' },
  { name: 'Iran', value: 'IR' },
  { name: 'Iraq', value: 'IQ' },
  { name: 'Ireland', value: 'IE' },
  { name: 'Israel', value: 'IL' },
  { name: 'Italy', value: 'IT' },
  { name: 'Jamaica', value: 'JM' },
  { name: 'Japan', value: 'JP' },
  { name: 'Jordan', value: 'JO' },
  { name: 'Kazakhstan', value: 'KZ' },
  { name: 'Kenya', value: 'KE' },
  { name: 'Kiribati', value: 'KI' },
  { name: 'NorthKorea', value: 'KP' },
  { name: 'SouthKorea', value: 'KR' },
  { name: 'Kuwait', value: 'KW' },
  { name: 'Kyrgyzstan', value: 'KG' },
  { name: 'Laos', value: 'LA' },
  { name: 'Latvia', value: 'LV' },
  { name: 'Lebanon', value: 'LB' },
  { name: 'Lesotho', value: 'LS' },
  { name: 'Liberia', value: 'LR' },
  { name: 'Libya', value: 'LY' },
  { name: 'Liechtenstein', value: 'LI' },
  { name: 'Lithuania', value: 'LT' },
  { name: 'Luxembourg', value: 'LU' },
  { name: 'Macau', value: 'MO' },
  { name: 'Macedonia', value: 'MK' },
  { name: 'Madagascar', value: 'MG' },
  { name: 'Malawi', value: 'MW' },
  { name: 'Malaysia', value: 'MY' },
  { name: 'Maldives', value: 'MV' },
  { name: 'Mali', value: 'ML' },
  { name: 'Malta', value: 'MT' },
  { name: 'MarshallIslands', value: 'MH' },
  { name: 'Mauritania', value: 'MR' },
  { name: 'Mauritius', value: 'MU' },
  { name: 'Mexico', value: 'MX' },
  { name: 'Micronesia', value: 'FM' },
  { name: 'Moldova', value: 'MD' },
  { name: 'Monaco', value: 'MC' },
  { name: 'Mongolia', value: 'MN' },
  { name: 'Montenegro', value: 'ME' },
  { name: 'Morocco', value: 'MA' },
  { name: 'Mozambique', value: 'MZ' },
  { name: 'Myanmar', value: 'MM' },
  { name: 'Namibia', value: 'NA' },
  { name: 'Nauru', value: 'NR' },
  { name: 'Nepal', value: 'NP' },
  { name: 'Netherlands', value: 'NL' },
  { name: 'NewZealand', value: 'NZ' },
  { name: 'Nicaragua', value: 'NI' },
  { name: 'Niger', value: 'NE' },
  { name: 'Nigeria', value: 'NG' },
  { name: 'Norway', value: 'NO' },
  { name: 'Oman', value: 'OM' },
  { name: 'Pakistan', value: 'PK' },
  { name: 'Palau', value: 'PW' },
  { name: 'Panama', value: 'PA' },
  { name: 'PapuaNewGuinea', value: 'PG' },
  { name: 'Paraguay', value: 'PY' },
  { name: 'Peru', value: 'PE' },
  { name: 'Philippines', value: 'PH' },
  { name: 'Poland', value: 'PL' },
  { name: 'Portugal', value: 'PT' },
  { name: 'Qatar', value: 'QA' },
  { name: 'Romania', value: 'RO' },
  { name: 'Russia', value: 'RU' },
  { name: 'Rwanda', value: 'RW' },
  { name: 'SaintKittsAndNevis', value: 'KN' },
  { name: 'SaintLucia', value: 'LC' },
  { name: 'SaintVincentAndGrenadines', value: 'VC' },
  { name: 'Samoa', value: 'WS' },
  { name: 'SanMarino', value: 'SM' },
  { name: 'SaoTomeAndPrincipe', value: 'ST' },
  { name: 'SaudiArabia', value: 'SA' },
  { name: 'Senegal', value: 'SN' },
  { name: 'Serbia', value: 'RS' },
  { name: 'Seychelles', value: 'SC' },
  { name: 'SierraLeone', value: 'SL' },
  { name: 'Singapore', value: 'SG' },
  { name: 'Slovakia', value: 'SK' },
  { name: 'Slovenia', value: 'SI' },
  { name: 'SolomonIslands', value: 'SB' },
  { name: 'Somalia', value: 'SO' },
  { name: 'SouthAfrica', value: 'ZA' },
  { name: 'Spain', value: 'ES' },
  { name: 'SriLanka', value: 'LK' },
  { name: 'Sudan', value: 'SD' },
  { name: 'Suriname', value: 'SR' },
  { name: 'Swaziland', value: 'SZ' },
  { name: 'Sweden', value: 'SE' },
  { name: 'Switzerland', value: 'CH' },
  { name: 'Syria', value: 'SY' },
  { name: 'Taiwan', value: 'TW' },
  { name: 'Tajikistan', value: 'TJ' },
  { name: 'Tanzania', value: 'TZ' },
  { name: 'Thailand', value: 'TH' },
  { name: 'TimorLeste', value: 'TL' },
  { name: 'Togo', value: 'TG' },
  { name: 'Tonga', value: 'TO' },
  { name: 'TrinidadAndTobago', value: 'TT' },
  { name: 'Tunisia', value: 'TN' },
  { name: 'Turkey', value: 'TR' },
  { name: 'Turkmenistan', value: 'TM' },
  { name: 'Tuvalu', value: 'TV' },
  { name: 'USVirginIslands', value: 'VI' },
  { name: 'Uganda', value: 'UG' },
  { name: 'Ukraine', value: 'UA' },
  { name: 'UnitedArabEmirates', value: 'AE' },
  { name: 'UnitedKingdom', value: 'GB' },
  { name: 'UnitedStates', value: 'US' },
  { name: 'Uruguay', value: 'UY' },
  { name: 'Uzbekistan', value: 'UZ' },
  { name: 'Vanuatu', value: 'VU' },
  { name: 'VaticanCity', value: 'VA' },
  { name: 'Venezuela', value: 'VE' },
  { name: 'Vietnam', value: 'VN' },
  { name: 'Yemen', value: 'YE' },
  { name: 'Zambia', value: 'ZM' },
  { name: 'Zimbabwe', value: 'ZW' },
  { name: 'Kosovo', value: 'XK' },
  { name: 'SouthSudan', value: 'SS' },
  { name: 'Palestine', value: 'PS' },
  { name: 'Curacao', value: 'CW' },
  { name: 'Gibraltar', value: 'GI' },
  { name: 'NewCaledonia', value: 'NC' },
  { name: 'CookIslands', value: 'CK' },
  { name: 'Reunion', value: 'RE' },
  { name: 'Guernsey', value: 'GG' },
  { name: 'Guadeloupe', value: 'GP' },
  { name: 'Martinique', value: 'MQ' },
  { name: 'FrenchPolynesia', value: 'PF' },
  { name: 'FaroeIslands', value: 'FO' },
  { name: 'Greenland', value: 'GL' },
  { name: 'Jersey', value: 'JE' },
  { name: 'Aruba', value: 'AW' },
  { name: 'PuertoRico', value: 'PR' },
  { name: 'IsleOfMan', value: 'IM' },
  { name: 'Guam', value: 'GU' },
  { name: 'SintMaarten', value: 'SX' },
  { name: 'TurksAndCaicos', value: 'TC' },
  { name: 'AlandIslands', value: 'AX' },
  { name: 'CaribbeanNetherlands', value: 'BQ' },
  { name: 'BritishIndianOceanTerritory', value: 'IO' },
  { name: 'ChristmasIsland', value: 'CX' },
  { name: 'CocosIslands', value: 'CC' },
  { name: 'FalklandIslands', value: 'FK' },
  { name: 'Mayotte', value: 'YT' },
  { name: 'Niue', value: 'NU' },
  { name: 'NorfolkIsland', value: 'NF' },
  { name: 'NorthernMarianaIslands', value: 'MP' },
  { name: 'PitcairnIslands', value: 'PN' },
  { name: 'SaintHelenaAscensionTristanDaCunha', value: 'SH' },
  { name: 'SaintMartin', value: 'MF' },
  { name: 'SaintPierreAndMiquelon', value: 'PM' },
  { name: 'Tokelau', value: 'TK' },
  { name: 'WallisAndFutuna', value: 'WF' },
  { name: 'AmericanSamoa', value: 'AS' },
];

export const ttTransferStatusEnum: any = {
  0: 'Pending',
  1: 'Completed',
  2: 'Declined',
  3: 'Processing',
  4: 'PartiallyExecuted',
  5: 'ManualTransfer',
};
export const stTransferStatusEnum: any = {
  0: 'Pending',
  1: 'Completed',
  2: 'Declined',
  3: 'WaitingBankResponse',
  4: 'ManualTransaction',
};

export const allTBanksEnum: any = {
  '001': 'Türkiye Cumhuriyet Merkez Bankası A.Ş.',
  '004': 'İller Bankası',
  '010': 'Türkiye Cumhuriyeti Ziraat Bankası A.Ş.',
  '012': 'Türkiye Halk Bankası A.Ş.',
  '013': 'Denizbank',
  '014': 'Türkiye Sınai Kalkınma Bankası A.Ş.',
  '015': 'Türkiye Vakıflar Bankası T.A.O.',
  '016': 'Türkiye İhracat Kredi Bankası A.Ş. (Eximbank)',
  '017': 'Türkiye Kalkınma Bankası A.Ş.',
  '029': 'Birleşik Fon Bankası A.Ş. (Bayındırbank A.Ş.)',
  '032': 'Türk Ekonomi Bankası A.Ş.',
  '034': 'Aktif Yatırım Bankası A.Ş.',
  '046': 'Akbank T.A.Ş.',
  '048': 'HSBC Bank A.Ş.',
  '058': 'Sınai Yatırım Bankası A.Ş.',
  '059': 'Şekerbank T.A.Ş.',
  '062': 'Türkiye Garanti Bankası A.Ş.',
  '064': 'Türkiye İş Bankası A.Ş.',
  '067': 'Yapı ve Kredi Bankası A.Ş.',
  '071': 'Fortis Bank (TEB)',
  '087': 'Banca di Roma',
  '088': 'The Royal Bank of Scotland PLC Merkezi Amsterdam İstanbul Merkez Şubesi',
  '091': 'Arap Türk Bankası A.Ş.',
  '092': 'Citibank N.A.',
  '094': 'Bank Mellat',
  '095': 'BCCI',
  '096': 'Turkish Bank A.Ş.',
  '097': 'Habib Bank Limited',
  '098': 'JP Morgan Chase Bank İstanbul Türkiye Şubesi',
  '099': 'Oyak Bank A.Ş. - ING BANK',
  '100': 'Adabank A.Ş.',
  '101': 'Türk Sakura Bank A.Ş.',
  '103': 'Fiba Bank A.Ş.',
  '104': 'IMPEXBANK',
  '106': 'PORTIGON A.G.',
  '107': 'BNP-Ak-Dresdner Bank A.Ş.',
  '108': 'Turkland Bank A.Ş.',
  '109': 'Tekstil Bankası A.Ş.',
  '110': 'Credit Lyonnais',
  '111': 'Finansbank A.Ş.',
  '113': 'Marbank',
  '115': 'Deutsche Bank A.Ş.',
  '116': 'TAİB Yatırım Bank A.Ş.',
  '117': 'Turizm Yatırım ve Ticaret Bank A.Ş.',
  '118': 'Kıbrıs Kredi Bankası',
  '119': 'Birleşik Yatırım',
  '121': 'Standard Chartered Yatırım Bankası Türk A.Ş.',
  '122': 'Societe Generale',
  '123': 'HSBC Bank A.Ş.',
  '124': 'Alternatifbank A.Ş.',
  '125': 'Burganbank A.Ş.',
  '127': 'KentBank',
  '128': 'Park Yatırım Bankası',
  '129': 'Tat Yatırım Bankası A.Ş.',
  '132': 'IMKB Takas ve Saklama Bankası A.Ş.',
  '133': 'ING BANK',
  '134': 'Denizbank A.Ş.',
  '135': 'Anadolubank A.Ş.',
  '136': 'Okan Yatırım Bankası A Ş',
  '137': 'Rabobank Nederland İstanbul Merkez Şubesi',
  '138': 'Diler Yatırım Bankası A.Ş.',
  '139': 'GSD Yatırım Bankası A.Ş.',
  '140': 'Credit Suisse First Boston İstanbul Şubesi',
  '141': 'Nurol Yatırım Bankası A.Ş.',
  '142': 'Bank Pozitif Kredi ve Kalkınma Bankası A.Ş.',
  '144': 'Atlas Yatırım Bankası A.Ş.',
  '145': 'Morgan Guarenty Trusy Company',
  '146': 'OdeaBank A.Ş.',
  '147': 'Bank of Tokyo -Mitsubishi UFJ Turkey A.Ş.',
  '148': 'Intesa SanPaolo SPA İtalya-İstanbul Merkez Şubesi',
  '203': 'Al Baraka Türk Katılım Bankası A.Ş.',
  '204': 'Family Finans Kurumu',
  '205': 'Kuveyt Türk Katılım Bankası A.Ş.',
  '206': 'Türkiye Finans Katılım Bankası A.Ş.',
  '208': 'Asya Katılım Bankası A.Ş.',
  '210': 'Vakıf Katılım Bankası A.Ş.',
  '223': 'Al Baraka Türk Katılım Bankası A.Ş.',
};

export const transactionStatusEnum: any = [
  { value: 0, label: 'CurrentStatus ' },
  { value: 1, label: 'Rejected ' },
  { value: 2, label: 'Successful ' },
];

export const refundStatusEnum: any = [
  { value: 0, label: 'CurrentStatus ' },
  { value: 1, label: 'RefundCancelled ' },
  { value: 2, label: 'RefundManual ' },
  { value: 3, label: 'RefundAgain ' },
];
